### ISSUE TITLE
Model Structure

### ISSUE THREAD

**Issue by layumi** [wasidennis/AdaptSegNet#60]
Dear author, 

Thank you for your great code. I find an error in ASPP Classifier. https://github.com/wasidennis/AdaptSegNet/blob/master/model/deeplab_multi.py#L114-L118

```python
    def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list) - 1):
            out += self.conv2d_list[i + 1](x)
        return out  # Remove extra space
```

**Comment by wasidennis** [comment]
Yes, this was a bug and was fixed by the reference repo [link](https://github.com/wasidennis/AdaptSegNet/issues/4#issuecomment-391485393).

The bug is essentially making our model have only 2 effective ASPP layer, and we don't think it will affect the performance much. Note that, it may require other hyperparameters tuning if fixing this bug in our model.

**Comment by layumi** [comment]
@wasidennis  Thanks a lot.
