### ISSUE TITLE
Discriminator using ground truth instead of predictions from source domain

### ISSUE THREAD

**Issue by AshStuff** [wasidennis/AdaptSegNet#72]
Hello,
Did you try to use ground truth as a input to discriminator network instead of predictions from source domain. The discriminator can be powerful to distinguish the source and target in this case but it can also make the target domain close to source domain with more power. Just wondering if you tried it

**Comment by wasidennis** [comment]
To use ground truth as the input to the discriminator, it would be required to convert it to the one-hot encoding map, as the way we tried in the semi-supervised setting: https://github.com/hfslyc/AdvSemiSeg.

We have not tried it in this work, but due to the requirement of such conversion, it may not be effective as there would be a distribution gap between source ground truth and target prediction, which may make the discriminator's job easier.
