### ISSUE TITLE
Symbols of arguments confused.Source_label=0? and target_label=1? 

### ISSUE THREAD

**Issue by YFZh** [wasidennis/AdaptSegNet#8]
1. I found **"train_gta2cityscapes_multi.py"** has some mistakes in symbols of **arguments**,such as  the confusion between **iter_size** and **iter-size**

2.Besides,in line256,257 of **"train_gta2cityscapes_multi.py"**  :  source_label = 0    target_label = 1
Isn't it  on the contrary,that's said,source_label = 1    target_label = 0

**Comment by hfslyc** [comment]
Hi,

Thanks for interested in our work.

For 1., I think it's just our preference to use "-" in command line while the arg parser will translate "-" to "_".

For 2., I think our implementation is correct. Would you mind to explain more in details? I'm guessing that you have this question because of L320-326? If so, it's because that we need to use the opposite label to perform the adversarial training.

**Comment by YFZh** [comment]
Thank you for your reply.For 2,I noticed the opposite label used to perform the adversarial training.In fact,my question is ,in the article,you described,z = 0 if the sample is drawn from the target domain,
and z = 1 for the sample from the source domain.However,in the code,the label of the target domain is 1 and the label of the source domain is 0.(Maybe my understand isn't correct).Could it be understood as equivalent？

**Comment by wasidennis** [comment]
Thanks for noticing this! Yes, we accidentally put opposite labels in the paper, but the implementation is equivalent as you understood.
